package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTag<M extends BaseTag<M>> extends Model<M> implements IBean {

	public M setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
		return (M)this;
	}
	
	public java.lang.String getTagName() {
		return getStr("tag_name");
	}

	public M setDescb(java.lang.String descb) {
		set("descb", descb);
		return (M)this;
	}
	
	public java.lang.String getDescb() {
		return getStr("descb");
	}

	public M setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
		return (M)this;
	}
	
	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
