package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTermTagRel<M extends BaseTermTagRel<M>> extends Model<M> implements IBean {

	public M setShortName(java.lang.String shortName) {
		set("short_name", shortName);
		return (M)this;
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public M setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
		return (M)this;
	}
	
	public java.lang.String getTagName() {
		return getStr("tag_name");
	}

}
