package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTerm<M extends BaseTerm<M>> extends Model<M> implements IBean {

	public M setShortName(java.lang.String shortName) {
		set("short_name", shortName);
		return (M)this;
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public M setFullName(java.lang.String fullName) {
		set("full_name", fullName);
		return (M)this;
	}
	
	public java.lang.String getFullName() {
		return getStr("full_name");
	}

	public M setDescb(java.lang.String descb) {
		set("descb", descb);
		return (M)this;
	}
	
	public java.lang.String getDescb() {
		return getStr("descb");
	}

	public M setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
		return (M)this;
	}
	
	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public M setLastUpdate(java.util.Date lastUpdate) {
		set("last_update", lastUpdate);
		return (M)this;
	}
	
	public java.util.Date getLastUpdate() {
		return get("last_update");
	}

}
