package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tag", "tag_name", Tag.class);
		arp.addMapping("term", "short_name", Term.class);
		// Composite Primary Key order: short_name,tag_name
		arp.addMapping("term_tag_rel", "short_name,tag_name", TermTagRel.class);
	}
}

