package com.demo.common.model;

import com.demo.common.model.base.BaseTermTagRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TermTagRel extends BaseTermTagRel<TermTagRel> {
	public static final TermTagRel dao = new TermTagRel().dao();
}
